### ISSUE TITLE
Update header when user is logged in

### ISSUE THREAD

**Issue by antalasztrik** [feardevelopment/fear-frontend#28]
#### The logged in header should contain:
- Updated navigation bar
- Different functionality to logged in user

### The sub-tasks are the following:
- [x]  **Add logged in user functionality #34** 
- [x] **Create logged in navigation bar #33** 
    - [x] Create _user info_ menu item with the corresponding sub-pages. Issue: #29 
    - [x] Create _exams_ menu item with the corresponding sub-pages. Issue:  #32 
    - [x] Create _subjects_ menu item with the corresponding sub-pages. Issue:  #31 
    - [x] Create _studies_ menu item with the corresponding sub-pages. Issue:  #30

**Comment by antalasztrik** [comment]
Finished in #44
